Repository with-one-voice/ticketing-service, pull requests merged in 2025-04, with the labels that each got.

#3 Feature/#2 ci settings
  .github/workflows/ci.yml
  admin/src/test/java/com/onevoice/admin/AdminApplicationTests.java
  admin/src/test/resources/application-test.yml
  auth/build.gradle
  auth/src/main/resources/application.properties
  auth/src/main/resources/application.yml
  auth/src/test/java/com/onevoice/auth/AuthApplicationTests.java
  auth/src/test/resources/application-test.yml
  build.gradle
  notification/src/test/java/com/onevoice/notification/NotificationApplicationTests.java
  notification/src/test/resources/application-test.yml
  payment/src/test/java/com/onevoice/payment/PaymentApplicationTests.java
  payment/src/test/resources/application-test.yml
  seat/src/test/java/com/onevoice/seat/SeatApplicationTests.java
  seat/src/test/resources/application-test.yml
  show/src/test/java/com/onevoice/show/ShowApplicationTests.java
  show/src/test/resources/application-test.yml
  ticket/src/main/resources/application.properties
  ticket/src/main/resources/application.yml
  ticket/src/test/java/com/onevoice/ticket/TicketApplicationTests.java
  ticket/src/test/resources/application.yml
  user/src/test/java/com/onevoice/user/UserApplicationTests.java
  user/src/test/resources/application-test.yml
  venue/src/test/java/com/onevoice/venue/VenueApplicationTests.java
  venue/src/test/resources/application-test.yml
Labels: ci

#5 Feature/#4 add common module
  build.gradle
  common/.gitattributes
  common/.gitignore
  common/build.gradle
  common/gradle/wrapper/gradle-wrapper.jar
  common/gradle/wrapper/gradle-wrapper.properties
  common/gradlew
  common/gradlew.bat
  common/settings.gradle
  common/src/main/java/com/onevoice/common/CommonApplication.java
  common/src/main/java/com/onevoice/common/dto/CommonResponse.java
  common/src/main/java/com/onevoice/common/dto/ErrorResponse.java
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  common/src/main/java/com/onevoice/common/entity/BaseEntity.java
  common/src/main/java/com/onevoice/common/exception/BaseException.java
  common/src/main/java/com/onevoice/common/exception/GlobalExceptionHandler.java
  common/src/main/resources/application.yml
  common/src/test/java/com/onevoice/common/CommonApplicationTests.java
  settings.gradle
Labels: feat

#10 fix(#9):fix-config-server-error
  config/build.gradle
  config/src/main/resources/application.yml
  config/src/main/resources/config-repo/application.yml
  docker-compose.yml
  eureka/build.gradle
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  initdb/init-database.sql
Labels: fix

#11 fix(#9):fix-config-server-error
  config/src/main/resources/application.yml
  config/src/main/resources/config-repo/gateway-service.yml
Labels: fix

#13 chore(#12):chore-update-docker-compose
  docker-compose.yml
  initdb/init-database.sql
Labels: chore

#15 Feature/#14 add authentication
  auth/build.gradle
  auth/src/main/java/com/onevoice/auth/AuthApplication.java
  auth/src/main/java/com/onevoice/auth/application/client/UserClient.java
  auth/src/main/java/com/onevoice/auth/application/dto/FindUserQuery.java
  auth/src/main/java/com/onevoice/auth/application/service/AuthService.java
  auth/src/main/java/com/onevoice/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/onevoice/auth/infrastructure/config/SecurityConfig.java
  auth/src/main/java/com/onevoice/auth/infrastructure/jwt/JwtTokenProvider.java
  auth/src/main/java/com/onevoice/auth/presentation/AuthController.java
  auth/src/main/java/com/onevoice/auth/presentation/dto/request/LoginRequestDto.java
  auth/src/main/java/com/onevoice/auth/presentation/dto/request/SignupRequestDto.java
  auth/src/main/java/com/onevoice/auth/presentation/dto/response/LoginResponseDto.java
  auth/src/main/java/com/onevoice/auth/presentation/dto/response/SignupResponseDto.java
  auth/src/test/java/com/onevoice/auth/AuthApplicationTests.java
  build.gradle
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  config/src/main/resources/config-repo/auth-service.yml
  config/src/main/resources/config-repo/user-service.yml
  initdb/init-database.sql
  user/build.gradle
  user/src/main/java/com/onevoice/user/UserApplication.java
  user/src/main/java/com/onevoice/user/application/dto/FindUserQuery.java
  user/src/main/java/com/onevoice/user/application/dto/LoginRequestDto.java
  user/src/main/java/com/onevoice/user/application/dto/SignupRequestDto.java
  user/src/main/java/com/onevoice/user/application/service/UserService.java
  user/src/main/java/com/onevoice/user/application/service/UserServiceImpl.java
  user/src/main/java/com/onevoice/user/domain/User.java
  user/src/main/java/com/onevoice/user/domain/UserRole.java
  user/src/main/java/com/onevoice/user/domain/repository/UserRepository.java
  user/src/main/java/com/onevoice/user/domain/vo/Email.java
  user/src/main/java/com/onevoice/user/domain/vo/Password.java
  user/src/main/java/com/onevoice/user/exception/DuplicateUserException.java
  user/src/main/java/com/onevoice/user/exception/PasswordNotMatchException.java
  user/src/main/java/com/onevoice/user/exception/UserNotFoundException.java
  user/src/main/java/com/onevoice/user/infrastructure/UserRepositoryImpl.java
  user/src/main/java/com/onevoice/user/infrastructure/config/QuerydslConfig.java
  user/src/main/java/com/onevoice/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/onevoice/user/infrastructure/jpa/UserJpaRepository.java
  user/src/main/java/com/onevoice/user/presentation/UserController.java
Labels: feat

#31 feat(#16): 인증/인가 분리
  auth/build.gradle
  auth/src/main/java/com/onevoice/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/onevoice/auth/infrastructure/config/SecurityConfig.java
  auth/src/main/java/com/onevoice/auth/infrastructure/jwt/JwtTokenProvider.java
  build.gradle
  common/build.gradle
  common/src/main/java/com/onevoice/common/security/AuthenticationUtils.java
  common/src/main/java/com/onevoice/common/security/CustomAuthorizationFilter.java
  common/src/main/java/com/onevoice/common/security/UserRole.java
  config/src/main/resources/config-repo/gateway-service.yml
  config/src/main/resources/config-repo/user-service.yml
  gateway/build.gradle
  gateway/src/main/java/com/onevoice/gateway/filter/CustomPostFilter.java
  gateway/src/main/java/com/onevoice/gateway/filter/CustomPreFilter.java
  gateway/src/main/java/com/onevoice/gateway/jwt/JwtUtils.java
  user/src/main/java/com/onevoice/user/application/service/UserServiceImpl.java
  user/src/main/java/com/onevoice/user/domain/User.java
  user/src/main/java/com/onevoice/user/domain/UserRole.java
  user/src/main/java/com/onevoice/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/onevoice/user/presentation/UserController.java
Labels: chore

#33 Feature/#27 feat payments crud
  common/build.gradle
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  gradlew
  payment/build.gradle
  payment/src/main/java/com/onevoice/payment/application/dto/command/CreatePaymentCommand.java
  payment/src/main/java/com/onevoice/payment/application/dto/query/FindPaymentQuery.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentService.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/onevoice/payment/domain/Cancellation.java
  payment/src/main/java/com/onevoice/payment/domain/Payment.java
  payment/src/main/java/com/onevoice/payment/domain/PaymentMethod.java
  payment/src/main/java/com/onevoice/payment/domain/PaymentStatus.java
  payment/src/main/java/com/onevoice/payment/domain/Refund.java
  payment/src/main/java/com/onevoice/payment/domain/RefundStatus.java
  payment/src/main/java/com/onevoice/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/onevoice/payment/exception/PaymentNotFoundException.java
  payment/src/main/java/com/onevoice/payment/infrastructure/PaymentRepositoryImpl.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/QuerydslConfig.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/onevoice/payment/infrastructure/jpa/PaymentJpaRepository.java
  payment/src/main/java/com/onevoice/payment/presentation/PaymentController.java
  payment/src/main/java/com/onevoice/payment/presentation/TestController.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/request/CancelPaymentRequest.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/request/CreatePaymentRequest.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/request/RefundPaymentRequest.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/response/CancelPaymentResponse.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/response/RefundPaymentResponse.java
  payment/src/test/java/com/onevoice/payment/PaymentApplicationTests.java
Labels: feat

#36 Feature/#29 feat venues crud
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  common/src/main/java/com/onevoice/common/entity/BaseEntity.java
  initdb/insert_venue.sql
  user/src/test/java/com/onevoice/user/UserApplicationTests.java
  venue/build.gradle
  venue/src/main/java/com/onevoice/venue/VenueApplication.java
  venue/src/main/java/com/onevoice/venue/application/dto/FindVenueQuery.java
  venue/src/main/java/com/onevoice/venue/application/service/VenueService.java
  venue/src/main/java/com/onevoice/venue/application/service/VenueServiceImpl.java
  venue/src/main/java/com/onevoice/venue/domain/Venue.java
  venue/src/main/java/com/onevoice/venue/domain/repository/VenueRepository.java
  venue/src/main/java/com/onevoice/venue/exception/DuplicateVenueException.java
  venue/src/main/java/com/onevoice/venue/exception/NotFoundVenueException.java
  venue/src/main/java/com/onevoice/venue/infrastructure/VenueRepositoryImpl.java
  venue/src/main/java/com/onevoice/venue/infrastructure/config/QuerydslConfig.java
  venue/src/main/java/com/onevoice/venue/infrastructure/config/SecurityConfig.java
  venue/src/main/java/com/onevoice/venue/infrastructure/jpa/VenueJpaRepository.java
  venue/src/main/java/com/onevoice/venue/presentation/VenueController.java
  venue/src/main/java/com/onevoice/venue/presentation/dto/request/CreateVenueRequestDto.java
  venue/src/main/java/com/onevoice/venue/presentation/dto/request/UpdateVenueRequestDto.java
  venue/src/main/java/com/onevoice/venue/presentation/dto/response/CreateVenueResponseDto.java
  venue/src/main/java/com/onevoice/venue/presentation/dto/response/UpdateVenueResponseDto.java
  venue/src/main/java/com/onevoice/venue/presentation/dto/response/VenueResponseDto.java
  venue/src/test/java/com/onevoice/venue/VenueApplicationTests.java
Labels: feat

#38 Feature/#34 feat notification crud
  .gitignore
  config/src/main/resources/config-repo/notification-service.yml
  notification/.gitignore
  notification/build.gradle
  notification/src/main/java/com/onevoice/notification/application/client/UserClient.java
  notification/src/main/java/com/onevoice/notification/application/dto/command/CreateNotificationCommand.java
  notification/src/main/java/com/onevoice/notification/application/dto/message/EmailMessage.java
  notification/src/main/java/com/onevoice/notification/application/dto/query/FindNotificationQuery.java
  notification/src/main/java/com/onevoice/notification/application/dto/query/FindUserQuery.java
  notification/src/main/java/com/onevoice/notification/application/dto/query/ListNotificationQuery.java
  notification/src/main/java/com/onevoice/notification/application/event/EmailSendEvent.java
  notification/src/main/java/com/onevoice/notification/application/service/NotificationService.java
  notification/src/main/java/com/onevoice/notification/application/service/NotificationServiceImpl.java
  notification/src/main/java/com/onevoice/notification/domain/Notification.java
  notification/src/main/java/com/onevoice/notification/domain/NotificationStatus.java
  notification/src/main/java/com/onevoice/notification/domain/NotificationType.java
  notification/src/main/java/com/onevoice/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/onevoice/notification/exception/NotificationNotFoundException.java
  notification/src/main/java/com/onevoice/notification/infrastructure/NotificationRepositoryImpl.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/FeignConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/JpaAuditAware.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/SecurityConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/email/EventListener.java
  notification/src/main/java/com/onevoice/notification/infrastructure/jpa/NotificationJpaRepository.java
  notification/src/main/java/com/onevoice/notification/presentation/NotificationController.java
  notification/src/main/java/com/onevoice/notification/presentation/TestController.java
  notification/src/main/java/com/onevoice/notification/presentation/dto/request/CreateNotificationRequest.java
  notification/src/test/java/com/onevoice/notification/NotificationApplicationTests.java
  payment/.gitignore
Labels: feat

#37 Feature/#28 feat seats crud
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  seat/build.gradle
  seat/src/main/java/com/onevoice/seat/application/dto/CreateSeatCommand.java
  seat/src/main/java/com/onevoice/seat/application/dto/FindSeatQuery.java
  seat/src/main/java/com/onevoice/seat/application/dto/HoldSeatCommand.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatService.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/domain/Seat.java
  seat/src/main/java/com/onevoice/seat/domain/SeatStatus.java
  seat/src/main/java/com/onevoice/seat/domain/repository/SeatRepository.java
  seat/src/main/java/com/onevoice/seat/domain/vo/Money.java
  seat/src/main/java/com/onevoice/seat/domain/vo/SeatCode.java
  seat/src/main/java/com/onevoice/seat/domain/vo/SessionId.java
  seat/src/main/java/com/onevoice/seat/exception/SeatAlreadyHeldException.java
  seat/src/main/java/com/onevoice/seat/exception/SeatNotFoundException.java
  seat/src/main/java/com/onevoice/seat/infrastructure/config/QuerydslConfig.java
  seat/src/main/java/com/onevoice/seat/infrastructure/config/RedisConfig.java
  seat/src/main/java/com/onevoice/seat/infrastructure/config/SecurityConfig.java
  seat/src/main/java/com/onevoice/seat/infrastructure/persistence/SeatJpaRepository.java
  seat/src/main/java/com/onevoice/seat/infrastructure/persistence/SeatRepositoryImpl.java
  seat/src/main/java/com/onevoice/seat/presentation/SeatController.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/request/CreateSeatRequestDto.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/request/HoldSeatRequestDto.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/response/HoldSeatResponseDto.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/response/SeatResponseDto.java
  seat/src/test/java/com/onevoice/seat/SeatApplicationTests.java
  user/src/main/generated/com/onevoice/user/domain/QUser.java
  user/src/main/generated/com/onevoice/user/domain/vo/QEmail.java
  user/src/main/generated/com/onevoice/user/domain/vo/QPassword.java
Labels: feat

#39 Feature/#32 feat ticket crud
  common/build.gradle
  common/src/main/java/com/onevoice/common/config/FeignSecurityHeaderConfig.java
  common/src/main/java/com/onevoice/common/config/audit/AuditorAwareImpl.java
  common/src/main/java/com/onevoice/common/config/audit/JpaAuditingConfig.java
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  common/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  ticket/build.gradle
  ticket/src/main/java/com/onevoice/ticket/TicketApplication.java
  ticket/src/main/java/com/onevoice/ticket/application/client/SeatClient.java
  ticket/src/main/java/com/onevoice/ticket/application/client/ShowClient.java
  ticket/src/main/java/com/onevoice/ticket/application/client/UserClient.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/FindUserQuery.java
  ticket/src/main/java/com/onevoice/ticket/application/service/TicketService.java
  ticket/src/main/java/com/onevoice/ticket/application/service/TicketServiceImpl.java
  ticket/src/main/java/com/onevoice/ticket/domain/Ticket.java
  ticket/src/main/java/com/onevoice/ticket/domain/TicketStatus.java
  ticket/src/main/java/com/onevoice/ticket/domain/repository/TicketRepository.java
  ticket/src/main/java/com/onevoice/ticket/exception/RemoteUserNotFoundException.java
  ticket/src/main/java/com/onevoice/ticket/exception/TicketNotFoundException.java
  ticket/src/main/java/com/onevoice/ticket/exception/TicketOwnerMismatchException.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/TicketRepositoryImpl.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/config/QuerydslConfig.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/config/SecurityConfig.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/jpa/TicketJpaRepository.java
  ticket/src/main/java/com/onevoice/ticket/presentation/TicketController.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/request/CreateTicketRequestDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/request/UpdateTicketStatusRequestDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/CreateTicketResponseDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/DeleteTicketResponseDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/FindTicketResponseDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/ListReservedTicketResponseDto.java
  ticket/src/test/java/com/onevoice/ticket/TicketApplicationTests.java
  user/build.gradle
  user/src/main/java/com/onevoice/user/application/dto/FindUserQuery.java
  user/src/main/java/com/onevoice/user/application/service/UserService.java
  user/src/main/java/com/onevoice/user/application/service/UserServiceImpl.java
  user/src/main/java/com/onevoice/user/domain/User.java
  user/src/main/java/com/onevoice/user/presentation/UserController.java
Labels: feat, chore

#44 Feature/#17 feat show crud
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  show/build.gradle
  show/src/main/java/com/onevoice/show/application/dto/FindSessionQuery.java
  show/src/main/java/com/onevoice/show/application/dto/FindShowQuery.java
  show/src/main/java/com/onevoice/show/application/service/SessionService.java
  show/src/main/java/com/onevoice/show/application/service/SessionServiceImpl.java
  show/src/main/java/com/onevoice/show/application/service/ShowService.java
  show/src/main/java/com/onevoice/show/application/service/ShowServiceImpl.java
  show/src/main/java/com/onevoice/show/domain/Session.java
  show/src/main/java/com/onevoice/show/domain/Show.java
  show/src/main/java/com/onevoice/show/domain/ShowCategory.java
  show/src/main/java/com/onevoice/show/domain/Status.java
  show/src/main/java/com/onevoice/show/domain/repository/SessionRepository.java
  show/src/main/java/com/onevoice/show/domain/repository/ShowRepository.java
  show/src/main/java/com/onevoice/show/exception/DuplicateSessionException.java
  show/src/main/java/com/onevoice/show/exception/DuplicateShowException.java
  show/src/main/java/com/onevoice/show/exception/NotFoundSessionException.java
  show/src/main/java/com/onevoice/show/exception/NotFoundShowException.java
  show/src/main/java/com/onevoice/show/exception/TicketingAlreadyStartedException.java
  show/src/main/java/com/onevoice/show/infrastructure/SessionRepositoryImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/ShowRepositoryImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/config/QuerydslConfig.java
  show/src/main/java/com/onevoice/show/infrastructure/config/SecurityConfig.java
  show/src/main/java/com/onevoice/show/infrastructure/jpa/SessionJpaRepository.java
  show/src/main/java/com/onevoice/show/infrastructure/jpa/ShowJpaRepository.java
  show/src/main/java/com/onevoice/show/presentation/SessionController.java
  show/src/main/java/com/onevoice/show/presentation/ShowController.java
  show/src/main/java/com/onevoice/show/presentation/dto/request/CreateSessionRequestDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/request/CreateShowRequestDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/request/UpdateSessionRequestDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/request/UpdateShowRequestDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/CreateSessionResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/CreateShowResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/SessionResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/ShowResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/UpdateSessionResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/UpdateShowResponseDto.java
  show/src/test/java/com/onevoice/show/ShowApplicationTests.java
Labels: feat

#46 Feature/#40 feat payment etc
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  common/src/main/java/com/onevoice/common/entity/BaseEntity.java
  notification/src/main/java/com/onevoice/notification/NotificationApplication.java
  notification/src/main/java/com/onevoice/notification/application/client/UserClient.java
  notification/src/main/java/com/onevoice/notification/application/dto/message/EmailMessage.java
  notification/src/main/java/com/onevoice/notification/application/service/NotificationService.java
  notification/src/main/java/com/onevoice/notification/application/service/NotificationServiceImpl.java
  notification/src/main/java/com/onevoice/notification/domain/Notification.java
  notification/src/main/java/com/onevoice/notification/domain/NotificationStatus.java
  notification/src/main/java/com/onevoice/notification/domain/NotificationType.java
  notification/src/main/java/com/onevoice/notification/domain/repository/NotificationRepository.java
  notification/src/main/java/com/onevoice/notification/infrastructure/NotificationRepositoryImpl.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/CustomPageableArgumentResolver.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/EventConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/FeignConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/JpaAuditAware.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/SecurityConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/WebConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/email/EventListener.java
  notification/src/main/java/com/onevoice/notification/infrastructure/jpa/NotificationJpaRepository.java
  notification/src/main/java/com/onevoice/notification/presentation/NotificationController.java
  notification/src/main/java/com/onevoice/notification/presentation/TestController.java
  notification/src/main/java/com/onevoice/notification/presentation/dto/request/CreateNotificationRequest.java
  payment/src/main/java/com/onevoice/payment/PaymentApplication.java
  payment/src/main/java/com/onevoice/payment/application/dto/command/CreatePaymentCommand.java
  payment/src/main/java/com/onevoice/payment/application/dto/query/FindPaymentQuery.java
  payment/src/main/java/com/onevoice/payment/application/dto/query/ListPaymentQuery.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentService.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/onevoice/payment/domain/Cancellation.java
  payment/src/main/java/com/onevoice/payment/domain/Payment.java
  payment/src/main/java/com/onevoice/payment/domain/PaymentMethod.java
  payment/src/main/java/com/onevoice/payment/domain/PaymentStatus.java
  payment/src/main/java/com/onevoice/payment/domain/Refund.java
  payment/src/main/java/com/onevoice/payment/domain/RefundStatus.java
  payment/src/main/java/com/onevoice/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/onevoice/payment/exception/PaymentNotStatusException.java
  payment/src/main/java/com/onevoice/payment/infrastructure/PaymentRepositoryImpl.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/CustomPageableArgumentResolver.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/QuerydslConfig.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/WebConfig.java
  payment/src/main/java/com/onevoice/payment/infrastructure/jpa/PaymentJpaRepository.java
  payment/src/main/java/com/onevoice/payment/presentation/PaymentController.java
  payment/src/main/java/com/onevoice/payment/presentation/TestController.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/request/CancelPaymentRequest.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/request/CreatePaymentRequest.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/request/RefundPaymentRequest.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/response/CancelPaymentResponse.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/response/RefundPaymentResponse.java
Labels: feat

#48 Feature/#47 chore building monitoring
  admin/src/main/java/com/onevoice/admin/SecurityConfig.java
  auth/src/main/java/com/onevoice/auth/infrastructure/config/SecurityConfig.java
  build.gradle
  config/build.gradle
  config/src/main/resources/config-repo/admin-service.yml
  config/src/main/resources/config-repo/auth-service.yml
  config/src/main/resources/config-repo/gateway-service.yml
  config/src/main/resources/config-repo/notification-service.yml
  config/src/main/resources/config-repo/payment-service.yml
  config/src/main/resources/config-repo/seat-service.yml
  config/src/main/resources/config-repo/show-service.yml
  config/src/main/resources/config-repo/ticket-service.yml
  config/src/main/resources/config-repo/user-service.yml
  config/src/main/resources/config-repo/venue-service.yml
  docker-compose.yml
  eureka/build.gradle
  gateway/build.gradle
  initdb/01-init-database.sql
  initdb/02-insert_venue.sql
  notification/src/main/java/com/onevoice/notification/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/SecurityConfig.java
  prometheus.yml
  seat/src/main/java/com/onevoice/seat/infrastructure/config/SecurityConfig.java
  show/src/main/java/com/onevoice/show/infrastructure/config/SecurityConfig.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/config/SecurityConfig.java
  user/src/main/java/com/onevoice/user/infrastructure/config/SecurityConfig.java
  venue/src/main/java/com/onevoice/venue/infrastructure/config/SecurityConfig.java
Labels: feat, chore

#52 feat(49): add internal api
  ticket/src/main/java/com/onevoice/ticket/application/service/TicketService.java
  ticket/src/main/java/com/onevoice/ticket/presentation/TicketController.java
  ticket/src/main/java/com/onevoice/ticket/presentation/TicketInternalController.java
Labels: feat

#53 Feature/#41 feat seat etc
  seat/src/main/java/com/onevoice/seat/application/service/SeatService.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/domain/Seat.java
  seat/src/main/java/com/onevoice/seat/infrastructure/config/SecurityConfig.java
  seat/src/main/java/com/onevoice/seat/presentation/SeatController.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/request/HoldSeatRequestDto.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/response/SeatCreateResponseDto.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/response/SeatResponseDto.java
Labels: feat

#54 Feature/#45 show etc
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  show/src/main/java/com/onevoice/show/ShowApplication.java
  show/src/main/java/com/onevoice/show/application/client/SeatClient.java
  show/src/main/java/com/onevoice/show/application/client/VenueClient.java
  show/src/main/java/com/onevoice/show/application/dto/CreateSeatRequestDto.java
  show/src/main/java/com/onevoice/show/application/dto/SeatResponseDto.java
  show/src/main/java/com/onevoice/show/application/dto/VenueResponseDto.java
  show/src/main/java/com/onevoice/show/application/service/SessionService.java
  show/src/main/java/com/onevoice/show/application/service/SessionServiceImpl.java
  show/src/main/java/com/onevoice/show/application/service/ShowServiceImpl.java
  show/src/main/java/com/onevoice/show/exception/CancelledShowException.java
  show/src/main/java/com/onevoice/show/exception/InvalidSeatCountException.java
  show/src/main/java/com/onevoice/show/exception/InvalidSessionDateException.java
  show/src/main/java/com/onevoice/show/exception/InvalidVenueIdException.java
  show/src/main/java/com/onevoice/show/exception/SeatCreateApiFailException.java
  show/src/main/java/com/onevoice/show/presentation/ShowInternalController.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/SessionDetailResponseDto.java
  venue/src/main/java/com/onevoice/venue/VenueApplication.java
  venue/src/main/java/com/onevoice/venue/application/service/VenueServiceImpl.java
  venue/src/main/java/com/onevoice/venue/presentation/VenueController.java
  venue/src/main/java/com/onevoice/venue/presentation/VenueInternalController.java
Labels: feat

#56 Feature/#50 feat seat internal api
  seat/src/main/java/com/onevoice/seat/application/service/SeatService.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/domain/Seat.java
  seat/src/main/java/com/onevoice/seat/domain/repository/SeatRepository.java
  seat/src/main/java/com/onevoice/seat/infrastructure/config/SecurityConfig.java
  seat/src/main/java/com/onevoice/seat/infrastructure/persistence/SeatRepositoryImpl.java
  seat/src/main/java/com/onevoice/seat/presentation/SeatController.java
  seat/src/main/java/com/onevoice/seat/presentation/SeatInternalController.java
  seat/src/main/java/com/onevoice/seat/presentation/dto/request/SeatStatusChangeRequestDto.java
Labels: feat

#59 Feature/#45 show etc
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  show/build.gradle
  show/src/main/java/com/onevoice/show/ShowApplication.java
  show/src/main/java/com/onevoice/show/application/client/SeatClient.java
  show/src/main/java/com/onevoice/show/application/dto/SeatCreateResponseDto.java
  show/src/main/java/com/onevoice/show/application/service/SessionServiceImpl.java
  show/src/main/java/com/onevoice/show/application/service/ShowScheduler.java
  show/src/main/java/com/onevoice/show/application/service/ShowService.java
  show/src/main/java/com/onevoice/show/application/service/ShowServiceImpl.java
  show/src/main/java/com/onevoice/show/domain/Session.java
  show/src/main/java/com/onevoice/show/domain/Show.java
  show/src/main/java/com/onevoice/show/domain/Status.java
  show/src/main/java/com/onevoice/show/domain/repository/ShowRepository.java
  show/src/main/java/com/onevoice/show/exception/InvalidTicketingDateException.java
  show/src/main/java/com/onevoice/show/infrastructure/SessionRepositoryImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/ShowRepositoryImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/config/RedisConfig.java
  show/src/main/java/com/onevoice/show/infrastructure/config/ShedLockConfig.java
  show/src/main/java/com/onevoice/show/infrastructure/redis/RedisService.java
  show/src/main/java/com/onevoice/show/presentation/ShowInternalController.java
Labels: feat

#60 Feature/#58 feat additional monitoring
  .gitignore
  admin/src/main/resources/application.yml
  admin/src/main/resources/logback-spring.xml
  auth/src/main/resources/application.yml
  auth/src/main/resources/logback-spring.xml
  build.gradle
  config/src/main/resources/config-repo/admin-service.yml
  config/src/main/resources/config-repo/auth-service.yml
  config/src/main/resources/config-repo/gateway-service.yml
  config/src/main/resources/config-repo/notification-service.yml
  config/src/main/resources/config-repo/payment-service.yml
  config/src/main/resources/config-repo/seat-service.yml
  config/src/main/resources/config-repo/show-service.yml
  config/src/main/resources/config-repo/ticket-service.yml
  config/src/main/resources/config-repo/user-service.yml
  config/src/main/resources/config-repo/venue-service.yml
  docker-compose.yml
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  gateway/src/main/resources/logback-spring.xml
  gradlew
  loki-config.yaml
  notification/src/main/resources/application.yml
  notification/src/main/resources/logback-spring.xml
  payment/src/main/resources/application.yml
  payment/src/main/resources/logback-spring.xml
  promtail-config.yaml
  seat/src/main/resources/application.yml
  seat/src/main/resources/logback-spring.xml
  show/src/main/resources/application.yml
  show/src/main/resources/logback-spring.xml
  ticket/src/main/resources/application.yml
  ticket/src/main/resources/logback-spring.xml
  user/src/main/resources/application.yml
  user/src/main/resources/logback-spring.xml
  venue/src/main/resources/application.yml
  venue/src/main/resources/logback-spring.xml
Labels: feat, chore

#67 Feature/#64 feat payment apply kafka
  .gitignore
  common/build.gradle
  common/src/main/java/com/onevoice/common/config/FeignHttpConfig.java
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  config/src/main/resources/config-repo/notification-service.yml
  config/src/main/resources/config-repo/payment-service.yml
  docker-compose.yml
  initdb/02-init-table.sql
  initdb/03-insert_venue.sql
  notification/build.gradle
  notification/src/main/java/com/onevoice/notification/application/dto/message/EmailContext.java
  notification/src/main/java/com/onevoice/notification/application/event/EmailSendEvent.java
  notification/src/main/java/com/onevoice/notification/application/service/NotificationServiceImpl.java
  notification/src/main/java/com/onevoice/notification/domain/NotificationStatus.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/AsyncConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/CacheConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/EventConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/EmailEventListener.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/EmailSender.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/EmailServerChecker.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/KafkaConsumer.java
  payment/build.gradle
  payment/src/main/java/com/onevoice/payment/application/client/TicketClient.java
  payment/src/main/java/com/onevoice/payment/application/dto/client/UpdateTicketStatusRequestDto.java
  payment/src/main/java/com/onevoice/payment/application/dto/message/PaymentMessage.java
  payment/src/main/java/com/onevoice/payment/application/dto/message/TicketMessage.java
  payment/src/main/java/com/onevoice/payment/application/event/PaymentCreateEvent.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/EventConfig.java
  payment/src/main/java/com/onevoice/payment/infrastructure/message/PaymentEventListener.java
Labels: feat

#66 Feature/#62 feat seat concurrency control
  gradlew
  seat/build.gradle
  seat/src/main/java/com/onevoice/seat/SeatApplication.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatService.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/domain/repository/SeatRepository.java
  seat/src/main/java/com/onevoice/seat/infrastructure/config/RedissonConfig.java
  seat/src/main/java/com/onevoice/seat/infrastructure/persistence/SeatRepositoryImpl.java
  seat/src/main/java/com/onevoice/seat/infrastructure/scheduler/SeatHoldRecoveryScheduler.java
  seat/src/main/java/com/onevoice/seat/presentation/SeatController.java
  seat/src/main/java/com/onevoice/seat/presentation/SeatInternalController.java
Labels: feat

#72 Style/#71 chore prometheus path log
  common/src/main/java/com/onevoice/common/security/CustomAuthorizationFilter.java
  gateway/src/main/java/com/onevoice/gateway/filter/CustomPreFilter.java
Labels: style

#78 Feature/#74 feat payment apply saga
  common/src/main/java/com/onevoice/common/dto/ResponseCode.java
  common/src/main/java/com/onevoice/common/enumtype/KafkaTopicType.java
  config/src/main/resources/config-repo/notification-service.yml
  config/src/main/resources/config-repo/payment-service.yml
  notification/src/main/java/com/onevoice/notification/application/event/EmailNotificationEventPublisher.java
  notification/src/main/java/com/onevoice/notification/application/event/EmailSendEvent.java
  notification/src/main/java/com/onevoice/notification/application/event/NotificationEventPublisher.java
  notification/src/main/java/com/onevoice/notification/application/event/NotificationEventPublisherFactory.java
  notification/src/main/java/com/onevoice/notification/application/service/NotificationServiceImpl.java
  notification/src/main/java/com/onevoice/notification/domain/NotificationStatus.java
  notification/src/main/java/com/onevoice/notification/exception/NotificationUserNotFoundException.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/AsyncConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/EmailEventListener.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/EmailSender.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/KafkaConsumer.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/NotificationEmailConsumer.java
  payment/build.gradle
  payment/src/main/java/com/onevoice/payment/application/client/TicketClient.java
  payment/src/main/java/com/onevoice/payment/application/dto/client/FindTicketResponseDto.java
  payment/src/main/java/com/onevoice/payment/application/dto/client/UpdateTicketStatusRequestDto.java
  payment/src/main/java/com/onevoice/payment/application/dto/command/KakaoPayApproveCommand.java
  payment/src/main/java/com/onevoice/payment/application/dto/command/KakaoPayReadyCommand.java
  payment/src/main/java/com/onevoice/payment/application/dto/message/PaymentFailMessage.java
  payment/src/main/java/com/onevoice/payment/application/dto/message/PaymentMessage.java
  payment/src/main/java/com/onevoice/payment/application/dto/message/PaymentSuccessMessage.java
  payment/src/main/java/com/onevoice/payment/application/dto/message/TicketMessage.java
  payment/src/main/java/com/onevoice/payment/application/dto/query/FindPaymentQuery.java
  payment/src/main/java/com/onevoice/payment/application/dto/query/KakaoPayReadyQuery.java
  payment/src/main/java/com/onevoice/payment/application/event/GenericKafkaEvent.java
  payment/src/main/java/com/onevoice/payment/application/event/KafkaEvent.java
  payment/src/main/java/com/onevoice/payment/application/event/PaymentCreateEvent.java
  payment/src/main/java/com/onevoice/payment/application/service/KakaoPayService.java
  payment/src/main/java/com/onevoice/payment/application/service/KakaoPayServiceImpl.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentService.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/onevoice/payment/domain/Payment.java
  payment/src/main/java/com/onevoice/payment/domain/PaymentStatus.java
  payment/src/main/java/com/onevoice/payment/exception/PaymentNotStatusException.java
  payment/src/main/java/com/onevoice/payment/infrastructure/PaymentRepositoryImpl.java
  payment/src/main/java/com/onevoice/payment/infrastructure/config/SecurityConfig.java
  payment/src/main/java/com/onevoice/payment/infrastructure/jpa/PaymentJpaRepository.java
  payment/src/main/java/com/onevoice/payment/infrastructure/message/KafkaTransactionalEventPublisher.java
  payment/src/main/java/com/onevoice/payment/infrastructure/message/PaymentEventListener.java
  payment/src/main/java/com/onevoice/payment/presentation/KakaoPaymentController.java
  payment/src/main/java/com/onevoice/payment/presentation/dto/response/RefundPaymentResponse.java
  payment/src/main/resources/templates/approve.html
  payment/src/main/resources/templates/cancel.html
  payment/src/main/resources/templates/fail.html
  payment/src/main/resources/templates/index.html
  payment/src/main/resources/templates/ready.html
Labels: feat

#79 Feature/#76 feat seat apply saga
  config/src/main/resources/config-repo/seat-service.yml
  seat/build.gradle
  seat/src/main/java/com/onevoice/seat/application/dto/message/SeatConfirmedMessage.java
  seat/src/main/java/com/onevoice/seat/application/dto/message/SeatFailedMessage.java
  seat/src/main/java/com/onevoice/seat/application/dto/message/TicketConfirmFailedMessage.java
  seat/src/main/java/com/onevoice/seat/application/dto/message/TicketConfirmedMessage.java
  seat/src/main/java/com/onevoice/seat/application/event/GenericKafkaEvent.java
  seat/src/main/java/com/onevoice/seat/application/event/KafkaEvent.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatService.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/domain/Seat.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/KafkaTransactionalEventPublisher.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/TicketMessageConsumer.java
Labels: feat

#85 Feature/#65 feat advanced features apply
  common/src/main/java/com/onevoice/common/enumtype/KafkaTopicType.java
  config/src/main/resources/config-repo/show-service.yml
  docker-compose.yml
  seat/build.gradle
  seat/src/main/java/com/onevoice/seat/application/dto/message/SeatCreateFailMessage.java
  seat/src/main/java/com/onevoice/seat/application/dto/message/SeatCreateRequestMessage.java
  seat/src/main/java/com/onevoice/seat/application/dto/message/SeatCreateSuccessMessage.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/SeatEventProducer.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/ShowCreateRequestConsumer.java
  show/build.gradle
  show/src/main/java/com/onevoice/show/application/client/SeatClient.java
  show/src/main/java/com/onevoice/show/application/client/VenueClient.java
  show/src/main/java/com/onevoice/show/application/dto/SeatResponseDto.java
  show/src/main/java/com/onevoice/show/application/dto/client/SeatCreateRequestDto.java
  show/src/main/java/com/onevoice/show/application/dto/client/SeatCreateResponseDto.java
  show/src/main/java/com/onevoice/show/application/dto/client/VenueResponseDto.java
  show/src/main/java/com/onevoice/show/application/dto/message/SeatCreateFailMessage.java
  show/src/main/java/com/onevoice/show/application/dto/message/SeatCreateRequestMessage.java
  show/src/main/java/com/onevoice/show/application/dto/message/SeatCreateSuccessMessage.java
  show/src/main/java/com/onevoice/show/application/dto/query/FindSessionQuery.java
  show/src/main/java/com/onevoice/show/application/dto/query/FindShowQuery.java
  show/src/main/java/com/onevoice/show/application/event/GenericKafkaEvent.java
  show/src/main/java/com/onevoice/show/application/event/KafkaEvent.java
  show/src/main/java/com/onevoice/show/application/service/Scheduler.java
  show/src/main/java/com/onevoice/show/application/service/ShowScheduler.java
  show/src/main/java/com/onevoice/show/application/service/session/SessionService.java
  show/src/main/java/com/onevoice/show/application/service/session/SessionServiceImpl.java
  show/src/main/java/com/onevoice/show/application/service/show/ShowService.java
  show/src/main/java/com/onevoice/show/application/service/show/ShowServiceImpl.java
  show/src/main/java/com/onevoice/show/domain/Session.java
  show/src/main/java/com/onevoice/show/infrastructure/SessionRepositoryImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/config/KafkaConfig.java
  show/src/main/java/com/onevoice/show/infrastructure/message/SeatEventConsumer.java
  show/src/main/java/com/onevoice/show/infrastructure/message/ShowEventPublisher.java
  show/src/main/java/com/onevoice/show/presentation/SessionController.java
  show/src/main/java/com/onevoice/show/presentation/ShowController.java
  show/src/main/java/com/onevoice/show/presentation/ShowInternalController.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/CreateSessionResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/CreateShowResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/SessionResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/ShowResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/UpdateSessionResponseDto.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/UpdateShowResponseDto.java
Labels: feat

#87 Feature/#83 feat ticket additional feature
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/message/PaymentMessageConsumer.java
Labels: fix

#88 Feature/#82 feat seat apply caching
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/domain/repository/SeatRepository.java
  seat/src/main/java/com/onevoice/seat/infrastructure/persistence/SeatJpaRepository.java
  seat/src/main/java/com/onevoice/seat/infrastructure/persistence/SeatRepositoryImpl.java
  seat/src/main/java/com/onevoice/seat/infrastructure/redis/RedisConfig.java
  seat/src/main/java/com/onevoice/seat/infrastructure/redis/RedisKeyUtil.java
  seat/src/main/java/com/onevoice/seat/infrastructure/redis/RedissonConfig.java
  seat/src/main/java/com/onevoice/seat/infrastructure/scheduler/SeatHoldRecoveryScheduler.java
Labels: feat, refactor

#89 Feature/#83 feat ticket additional feature
  show/src/main/java/com/onevoice/show/application/service/session/SessionServiceImpl.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/TicketConfirmedMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/service/TicketServiceImpl.java
  ticket/src/main/java/com/onevoice/ticket/domain/Ticket.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/TicketRepositoryImpl.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/request/CreateTicketRequestDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/CreateTicketResponseDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/FindTicketResponseDto.java
Labels: feat, fix

#90 Feature/#81 feat show apply caching
  config/src/main/resources/config-repo/seat-service.yml
  show/build.gradle
  show/src/main/java/com/onevoice/show/application/service/Scheduler.java
  show/src/main/java/com/onevoice/show/application/service/session/SessionServiceImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/SessionRepositoryImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/config/RedisConfig.java
  show/src/main/java/com/onevoice/show/infrastructure/redis/SessionCache.java
  show/src/main/java/com/onevoice/show/infrastructure/redis/SessionCacheEvict.java
  show/src/main/java/com/onevoice/show/infrastructure/redis/SessionCacheStore.java
  show/src/main/java/com/onevoice/show/presentation/dto/response/SessionDetailResponseDto.java
Labels: feat

#96 feat(#92): add kafka topic
  common/src/main/java/com/onevoice/common/enumtype/KafkaTopicType.java
  payment/src/main/java/com/onevoice/payment/application/dto/message/PaymentCreateMessage.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
Labels: feat

#98 Feature/#94 feat seat update kafka topic
  common/src/main/java/com/onevoice/common/enumtype/KafkaTopicType.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/TicketMessageConsumer.java
Labels: feat

#99 Feature/#93 feat ticket update kafka topic
  common/src/main/java/com/onevoice/common/enumtype/KafkaTopicType.java
  common/src/main/java/com/onevoice/common/enumtype/TicketStatus.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/message/PaymentCreateMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/message/PaymentFailMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/message/PaymentSuccessMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/message/SeatExpiredMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/message/TicketConfirmedMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/message/TicketFailedMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/dto/message/TicketStatusMessage.java
  ticket/src/main/java/com/onevoice/ticket/application/service/TicketService.java
  ticket/src/main/java/com/onevoice/ticket/application/service/TicketServiceImpl.java
  ticket/src/main/java/com/onevoice/ticket/domain/Ticket.java
  ticket/src/main/java/com/onevoice/ticket/domain/TicketSeat.java
  ticket/src/main/java/com/onevoice/ticket/domain/repository/TicketRepository.java
  ticket/src/main/java/com/onevoice/ticket/domain/repository/TicketSeatRepository.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/TicketRepositoryImpl.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/TicketSeatRepositoryImpl.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/jpa/TicketSeatJpaRepository.java
  ticket/src/main/java/com/onevoice/ticket/infrastructure/message/PaymentMessageConsumer.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/CreateTicketResponseDto.java
  ticket/src/main/java/com/onevoice/ticket/presentation/dto/response/FindTicketResponseDto.java
Labels: feat, fix

#100 Feature/#95 feat seat expired publish
  common/src/main/java/com/onevoice/common/enumtype/KafkaTopicType.java
  seat/src/main/java/com/onevoice/seat/application/dto/message/SeatExpiredMessage.java
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/SeatEventProducer.java
  seat/src/main/java/com/onevoice/seat/infrastructure/scheduler/SeatHoldRecoveryScheduler.java
Labels: feat

#102 Chore : redis-exporter 추가
  docker-compose.yml
  prometheus.yml
Labels: chore

#104 Feature/#103 feat notification update kafka topic
  config/src/main/resources/config-repo/notification-service.yml
  notification/src/main/java/com/onevoice/notification/application/client/DiscordClient.java
  notification/src/main/java/com/onevoice/notification/application/dto/message/DiscordMessage.java
  notification/src/main/java/com/onevoice/notification/application/dto/message/KafkaTopicMessage.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/handler/EmailNotificationHandler.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/handler/NotificationHandler.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/handler/PushNotificationHandler.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/kafka/NotificationTopicConsumer.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/kafka/SeatTopicConsumer.java
  notification/src/main/java/com/onevoice/notification/infrastructure/message/kafka/TicketTopicConsumer.java
  notification/src/test/java/com/onevoice/notification/NotificationApplicationTests.java
  notification/src/test/java/com/onevoice/notification/TestMailConfig.java
  payment/src/main/java/com/onevoice/payment/application/dto/command/KakaoPayReadyCommand.java
  payment/src/main/java/com/onevoice/payment/application/service/KakaoPayServiceImpl.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
Labels: feat

#105 Update notification-service.yml
  config/src/main/resources/config-repo/notification-service.yml
Labels: chore, style

#107 Refact/#106 refact change seat show response structure
  seat/src/main/java/com/onevoice/seat/application/service/SeatServiceImpl.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/SeatEventProducer.java
  seat/src/main/java/com/onevoice/seat/infrastructure/message/ShowCreateRequestConsumer.java
  show/src/main/java/com/onevoice/show/application/service/session/SessionServiceImpl.java
  show/src/main/java/com/onevoice/show/infrastructure/message/KafkaTransactionalEventPublisher.java
  show/src/main/java/com/onevoice/show/infrastructure/message/SeatEventConsumer.java
Labels: refactor

#112 Feature/#108 feat admin crud
  admin/src/main/java/com/onevoice/admin/AdminApplication.java
  admin/src/main/java/com/onevoice/admin/application/client/ShowClient.java
  admin/src/main/java/com/onevoice/admin/application/service/AdminService.java
  admin/src/main/java/com/onevoice/admin/application/service/AdminServiceImpl.java
  admin/src/main/java/com/onevoice/admin/infrastructure/config/SecurityConfig.java
  admin/src/main/java/com/onevoice/admin/presentation/controller/AdminController.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/session/AdminCreateSessionRequest.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/session/AdminCreateSessionResponse.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/session/AdminSessionDetailResponse.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/session/AdminSessionResponse.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/session/AdminUpdateSessionRequest.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/session/AdminUpdateSessionResponse.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/show/AdminCreateShowRequest.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/show/AdminCreateShowResponse.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/show/AdminShowDetailResponse.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/show/AdminShowResponse.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/show/AdminUpdateShowRequest.java
  admin/src/main/java/com/onevoice/admin/presentation/dto/client/show/AdminUpdateShowResponse.java
  seat/src/main/java/com/onevoice/seat/infrastructure/scheduler/SeatHoldRecoveryScheduler.java
  show/src/main/java/com/onevoice/show/presentation/ShowInternalController.java
Labels: feat

#118 Fix/#114 feat monitoring more improvement
  admin/k8s/deployment.yml
  auth/k8s/deployment.yml
  gateway/k8s/deployment.yml
  helm/monitoring/templates/_helpers.tpl
  notification/k8s/deployment.yml
  payment/k8s/deployment.yml
  seat/k8s/deployment.yml
  show/k8s/deployment.yml
  ticket/k8s/deployment.yml
  user/k8s/deployment.yml
  venue/k8s/deployment.yml
Labels: fix

#122 Feature/#121-add-fronted-login
  auth/src/main/java/com/onevoice/auth/application/service/AuthService.java
  auth/src/main/java/com/onevoice/auth/application/service/AuthServiceImpl.java
  auth/src/main/java/com/onevoice/auth/presentation/AuthController.java
  auth/src/main/java/com/onevoice/auth/presentation/dto/response/LoginV2ResponseDto.java
Labels: feat

#125 Chore/#124 chore add redis
  config/src/main/resources/config-repo/auth-service.yml
  config/src/main/resources/config-repo/gateway-service.yml
  config/src/main/resources/config-repo/notification-service.yml
Labels: chore

#127 Feature/#126 fix swagger uri fix
  config/src/main/resources/config-repo/admin-service.yml
  config/src/main/resources/config-repo/auth-service.yml
  config/src/main/resources/config-repo/notification-service.yml
  config/src/main/resources/config-repo/payment-service.yml
  config/src/main/resources/config-repo/seat-service.yml
  config/src/main/resources/config-repo/show-service.yml
  config/src/main/resources/config-repo/ticket-service.yml
  config/src/main/resources/config-repo/user-service.yml
  config/src/main/resources/config-repo/venue-service.yml
Labels: fix

#129 fix(#125): add redis config
  auth/src/main/java/com/onevoice/auth/infrastructure/config/RedisConfig.java
  gateway/src/main/java/com/onevoice/gateway/config/RedisConfig.java
  notification/src/main/java/com/onevoice/notification/infrastructure/config/CacheConfig.java
Labels: fix

#130 chore(#114): chore redis config
  config/src/main/resources/config-repo/auth-service.yml
  config/src/main/resources/config-repo/gateway-service.yml
  config/src/main/resources/config-repo/notification-service.yml
Labels: fix, chore

#132 chore(#131): add redis config for kubenetis deployment
  auth/k8s/deployment.yml
  gateway/k8s/deployment.yml
  notification/k8s/deployment.yml
Labels: chore

#134 refact(#133) : 티켓 저장 로직 변경
  ticket/src/main/java/com/onevoice/ticket/application/service/TicketServiceImpl.java
Labels: refactor

#138 chore(#137): kakaopay uri
  payment/k8s/deployment.yml
Labels: chore

#140 feat(#139): add payment api
  payment/src/main/java/com/onevoice/payment/application/dto/query/ListPaymentQuery.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentService.java
  payment/src/main/java/com/onevoice/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/onevoice/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/onevoice/payment/infrastructure/PaymentRepositoryImpl.java
  payment/src/main/java/com/onevoice/payment/infrastructure/jpa/PaymentJpaRepository.java
  payment/src/main/java/com/onevoice/payment/presentation/PaymentController.java
Labels: feat

#141 Refactor/#114 refactor monitoring more improvement
  admin/k8s/deployment.yml
  admin/k8s/service-monitor.yml
  admin/k8s/service.yml
  auth/k8s/deployment.yml
  auth/k8s/service-monitor.yml
  auth/k8s/service.yml
  gateway/k8s/deployment.yml
  gateway/k8s/service-monitor.yml
  gateway/k8s/service.yml
  helm/monitoring/Chart.yaml
  helm/monitoring/README.md
  helm/monitoring/grafana-values.yaml
  helm/monitoring/loki-values.yaml
  helm/monitoring/service-grafana-lb.yaml
  helm/monitoring/templates/grafana/configmap.yaml
  helm/monitoring/templates/grafana/datasources-configmap.yaml
  helm/monitoring/templates/grafana/deployment.yaml
  helm/monitoring/templates/grafana/service.yaml
  helm/monitoring/templates/loki/configmap.yaml
  helm/monitoring/templates/loki/deployment.yaml
  helm/monitoring/templates/loki/service.yaml
  helm/monitoring/templates/prometheus/configmap.yaml
  helm/monitoring/templates/prometheus/deployment.yaml
  helm/monitoring/templates/prometheus/service.yaml
  helm/monitoring/values.yaml
  notification/k8s/deployment.yml
  notification/k8s/service-monitor.yml
  notification/k8s/service.yml
  payment/k8s/deployment.yml
  payment/k8s/service-monitor.yml
  payment/k8s/service.yml
  seat/k8s/deployment.yml
  seat/k8s/service-monitor.yml
  seat/k8s/service.yml
  show/k8s/deployment.yml
  show/k8s/service-monitor.yml
  show/k8s/service.yml
  ticket/k8s/deployment.yml
  ticket/k8s/service-monitor.yml
  ticket/k8s/service.yml
  user/k8s/deployment.yml
  user/k8s/service-monitoring.yml
  user/k8s/service.yml
  venue/k8s/deployment.yml
  venue/k8s/service-monitoring.yml
  venue/k8s/service.yml
Labels: feat, refactor

#145 feat(#143): update CD
  .github/workflows/deploy-admin.yml
  .github/workflows/deploy-auth.yml
  .github/workflows/deploy-config.yml
  .github/workflows/deploy-env.yml
  .github/workflows/deploy-eureka.yml
  .github/workflows/deploy-gateway.yml
  .github/workflows/deploy-notification.yml
  .github/workflows/deploy-payment.yml
  .github/workflows/deploy-seat.yml
  .github/workflows/deploy-show.yml
  .github/workflows/deploy-ticket.yml
  .github/workflows/deploy-user.yml
  .github/workflows/deploy-venue.yml
Labels: fix

#146 fix(#143): rollout restart변경
  .github/workflows/deploy-admin.yml
  .github/workflows/deploy-auth.yml
  .github/workflows/deploy-config.yml
  .github/workflows/deploy-eureka.yml
  .github/workflows/deploy-gateway.yml
  .github/workflows/deploy-notification.yml
  .github/workflows/deploy-payment.yml
  .github/workflows/deploy-seat.yml
  .github/workflows/deploy-show.yml
  .github/workflows/deploy-ticket.yml
  .github/workflows/deploy-user.yml
  .github/workflows/deploy-venue.yml
Labels: fix
